Practic/Models/Application.cs
using System;
using System.Collections.Generic;

namespace Practic.Models;

public partial class Application
{
    public int Id { get; set; }

    public int? FabricId { get; set; }

    public string ShortDescription { get; set; } = null!;

    public int? FirmId { get; set; }

    public int? CurrencyId { get; set; }

    public decimal Price { get; set; }

    public int Quantity { get; set; }

    public virtual Currency? Currency { get; set; } = null!;

    public virtual Fabric? Fabric { get; set; } = null!;

    public virtual Firm? Firm { get; set; } = null!;
}

Practic/ViewModels/ApplicationViewModel.cs
using Practic.Models;

namespace Practic.ViewModels
{
    public class ApplicationViewModel
    {
        public IEnumerable<Application> applications { get; set; }
        public PageViewModel PageViewModel { get; set; }

        public string Name { get; set; }

        public string ShortDescription { get; set; }

        public string NameofFirm { get; set; }

        public string NameofCurrency { get; set; }

        public decimal Price { get; set; }

        public int Quantity { get; set; }
    }
}

Practic/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.Evaluation;
using Microsoft.EntityFrameworkCore;
using Practic;
using Practic.Models;
using Practic.ViewModels;
using Practic.Infrastructure;
using static System.Net.Mime.MediaTypeNames;

namespace Practic.Controllers
{
    public class ApplicationsController : Controller
    {
        private readonly PracticdataContext _context;
        private readonly int pageSize = 6;

        public ApplicationsController(PracticdataContext context)
        {
            _context = context;
        }

        // GET: Applications
        public IActionResult Index(int page = 1)
        {
            var applicationView = HttpContext.Session.Get<ApplicationViewModel>("Application");
            if (applicationView == null)
            {
                applicationView = new ApplicationViewModel();
            }

            IQueryable<Models.Application> applicationsDbContext = _context.Applications.Include(o => o.Fabric).Include(o => o.Currency).Include(o => o.Firm);
            applicationsDbContext = Search(applicationsDbContext, applicationView.Name, applicationView.ShortDescription, applicationView.NameofFirm, applicationView.NameofCurrency
    , applicationView.Price, applicationView.Quantity);
            var count = applicationsDbContext.Count();
            applicationsDbContext = applicationsDbContext.Skip((page - 1) * pageSize).Take(pageSize);
            ApplicationViewModel applications = new ApplicationViewModel
            {
                applications = applicationsDbContext,
                PageViewModel = new PageViewModel(count, page, pageSize),
                Name = applicationView.Name,
                ShortDescription = applicationView.ShortDescription,
                NameofFirm = applicationView.NameofFirm,
                NameofCurrency = applicationView.NameofCurrency,
                Price = applicationView.Price,
                Quantity = applicationView.Quantity
            };
            return View(applications);
        }

        [HttpPost]
        public IActionResult Index(ApplicationViewModel applicationView)
        {
            HttpContext.Session.Set("Application", applicationView);

            return RedirectToAction("Index");
        }

        // GET: Applications/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var application = await _context.Applications
                .Include(a => a.Currency)
                .Include(a => a.Fabric)
                .Include(a => a.Firm)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (application == null)
            {
                return NotFound();
            }

            return View(application);
        }

        // GET: Applications/Create
        public IActionResult Create()
        {
            ViewData["CurrencyId"] = new SelectList(_context.Currencies, "Id", "NameofCurrency");
            ViewData["FabricId"] = new SelectList(_context.Fabrics, "Id", "Name");
            ViewData["FirmId"] = new SelectList(_context.Firms, "Id", "NameofFirm");
            return View();
        }

        // POST: Applications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FabricId,ShortDescription,FirmId,CurrencyId,Price,Quantity")] Models.Application application)
        {
            if (ModelState.IsValid)
            {
                _context.Add(application);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CurrencyId"] = new SelectList(_context.Currencies, "Id", "NameofCurrency", application.CurrencyId);
            ViewData["FabricId"] = new SelectList(_context.Fabrics, "Id", "Name", application.FabricId);
            ViewData["FirmId"] = new SelectList(_context.Firms, "Id", "NameofFirm", application.FirmId);
            return View(application);
        }

        // GET: Applications/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var application = await _context.Applications.FindAsync(id);
            if (application == null)
            {
                return NotFound();
            }
            ViewData["CurrencyId"] = new SelectList(_context.Currencies, "Id", "NameofCurrency", application.CurrencyId);
            ViewData["FabricId"] = new SelectList(_context.Fabrics, "Id", "Name", application.FabricId);
            ViewData["FirmId"] = new SelectList(_context.Firms, "Id", "NameofFirm", application.FirmId);
            return View(application);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FabricId,ShortDescription,FirmId,CurrencyId,Price,Quantity")] Models.Application application)
        {
            if (id != application.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(application);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationExists(application.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CurrencyId"] = new SelectList(_context.Currencies, "Id", "NameofCurrency", application.CurrencyId);
            ViewData["FabricId"] = new SelectList(_context.Fabrics, "Id", "Name", application.FabricId);
            ViewData["FirmId"] = new SelectList(_context.Firms, "Id", "NameofFirm", application.FirmId);
            return View(application);
        }

        // GET: Applications/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var application = await _context.Applications
                .Include(a => a.Currency)
                .Include(a => a.Fabric)
                .Include(a => a.Firm)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (application == null)
            {
                return NotFound();
            }

            return View(application);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var application = await _context.Applications.FindAsync(id);
            if (application != null)
            {
                _context.Applications.Remove(application);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApplicationExists(int id)
        {
            return _context.Applications.Any(e => e.Id == id);
        }

        private IQueryable<Models.Application> Search(IQueryable<Models.Application> applications, string Name, string ShortDescription,
           string NameofFirm, string NameofCurrency, decimal Price, int Quantity)
        {
            applications = applications.Where(o => o.Fabric.Name.Contains(Name ?? "")
           && (o.ShortDescription.Contains(ShortDescription ?? ""))
           && (o.Firm.NameofFirm.Contains(NameofFirm ?? ""))
           && (o.Currency.NameofCurrency.Contains(NameofCurrency ?? ""))
           && (o.Price == Price || Price == 0)
           && (o.Quantity == Quantity || Quantity == 0));

            return applications;
        }
    }
}

Practic/Views/Applications/Create.cshtml
@model Practic.Models.Application

@{
    ViewData["Title"] = "Create";
}

<h1>Создать</h1>

<h4>Заявка</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FabricId" class="control-label">Материал</label>
                <select asp-for="FabricId" class ="form-control" asp-items="ViewBag.FabricId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label">Краткое описание</label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirmId" class="control-label">Фирма</label>
                <select asp-for="FirmId" class ="form-control" asp-items="ViewBag.FirmId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CurrencyId" class="control-label">Валюта</label>
                <select asp-for="CurrencyId" class ="form-control" asp-items="ViewBag.CurrencyId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Цена</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label">Количество</label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Practic/Views/Applications/Delete.cshtml
@model Practic.Models.Application

@{
    ViewData["Title"] = "Delete";
}

<h1>Удалить</h1>
<div>
    <h4>Заявка</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Краткое описание
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class = "col-sm-2">
            Цена
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            Количество
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            Валюта
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Currency.NameofCurrency)
        </dd>
        <dt class = "col-sm-2">
            Материал
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fabric.Name)
        </dd>
        <dt class = "col-sm-2">
            Фирма
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Firm.NameofFirm)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Назад</a>
    </form>
</div>

Practic/Views/Applications/Details.cshtml
@model Practic.Models.Application

@{
    ViewData["Title"] = "Details";
}

<h1>Подробности</h1>

<div>
    <h4>Заявка</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Краткое описание
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class = "col-sm-2">
            Цена
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            Количество
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            Валюта
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Currency.NameofCurrency)
        </dd>
        <dt class = "col-sm-2">
            Материал
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fabric.Name)
        </dd>
        <dt class = "col-sm-2">
            Фирма
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Firm.NameofFirm)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Изменить</a> |
    <a asp-action="Index">Назад</a>
</div>

Practic/Views/Applications/Edit.cshtml
@model Practic.Models.Application

@{
    ViewData["Title"] = "Edit";
}

<h1>Изменить</h1>

<h4>Заявка</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FabricId" class="control-label">Материал</label>
                <select asp-for="FabricId" class="form-control" asp-items="ViewBag.FabricId"></select>
                <span asp-validation-for="FabricId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label">Краткое описание</label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirmId" class="control-label">Фирма</label>
                <select asp-for="FirmId" class="form-control" asp-items="ViewBag.FirmId"></select>
                <span asp-validation-for="FirmId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CurrencyId" class="control-label">Валюта</label>
                <select asp-for="CurrencyId" class="form-control" asp-items="ViewBag.CurrencyId"></select>
                <span asp-validation-for="CurrencyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Цена</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label">Количество</label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Practic/Views/Applications/Index.cshtml
@model Practic.ViewModels.ApplicationViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Заявка</h1>

<p>
    <a type="button" class="btn btn-primary" asp-action="Create">Создать</a>
</p>
<form class="form-control-plaintext" action="@Url.Action("Index","Applications")" method="post">
    Краткое описание:@Html.TextBox("ShortDescription", Model.ShortDescription)
    Цена:@Html.TextBox("Price", Model.Price, new { type = "number", step = 0.01 })
    Количество:@Html.TextBox("Quantity", Model.Quantity, new { type = "number", step = 1 })
    Валюта:@Html.TextBox("NameofCurrency", Model.NameofCurrency)
    Материал:@Html.TextBox("Name", Model.Name)
    Фирма:@Html.TextBox("NameofFirm", Model.NameofFirm)
    <input type="submit" class="btn btn-outline-dark" value="Найти"></input>
</form>
<table class="table">
    <thead>
        <tr class="table-primary">
            <th>
                Краткое описание
            </th>
            <th>
                Цена
            </th>
            <th>
                Количество
            </th>
            <th>
                Валюта
            </th>
            <th>
                Материал
            </th>
            <th>
                Фирма
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.applications) {
            <tr class="table-secondary">
            <td>
                @Html.DisplayFor(modelItem => item.ShortDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Currency.NameofCurrency)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Fabric.Name)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Firm.NameofFirm)
            </td>
            <td>
                    <a class="badge rounded-pill bg-primary" asp-action="Edit" asp-route-id="@item.Id">Изменить</a>
                    <br />
                    <a class="badge rounded-pill bg-light" asp-action="Details" asp-route-id="@item.Id">Подробности</a>
                    <br />
                    <a class="badge rounded-pill bg-danger" asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    <ul class="pagination">
    @if (Model.PageViewModel.HasPreviousPage)
    {
        <li class="page-item">
             <a class="page-link" asp-action="Index" asp-route-page="@(Model.PageViewModel.PageNumber - 1)">&laquo;</a>
        </li>
    }

    @for (int i = 1; i <= Model.PageViewModel.TotalPages; i++)
    {
        <li class="page-item">
            <a class="page-link" asp-action="Index" asp-route-page="@i" class="@(i == Model.PageViewModel.PageNumber ? "active" : "")">@i</a>
        </li>
    }

    @if (Model.PageViewModel.HasNextPage)
    {
        <li class="page-item">
            <a class="page-link" asp-action="Index" asp-route-page="@(Model.PageViewModel.PageNumber + 1)">&raquo;</a>
        </li>
    }
    </ul>
</div>