Practic/Controllers/FabricsController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Practic;
using Practic.Models;
using Practic.ViewModels;
using Practic.Infrastructure;

namespace Practic.Controllers
{
    public class FabricsController : Controller
    {
        private readonly PracticdataContext _context;
        private readonly int pageSize = 6;

        public FabricsController(PracticdataContext context)
        {
            _context = context;
        }

        // GET: Fabrics
        public IActionResult Index(int page = 1)
        {
            var fabricView = HttpContext.Session.Get<FabricViewModel>("Fabric");
            if (fabricView == null)
            {
                fabricView = new FabricViewModel();
            }

            IQueryable<Models.Fabric> fabricsDbContext = _context.Fabrics.Include(o => o.SetviceName).Include(o => o.ForWhat);
            fabricsDbContext = Search(fabricsDbContext, fabricView.Name, fabricView.NameofService, fabricView.TypeofWork, fabricView.CodeTnved
    , fabricView.CodeOkrb);
            var count = fabricsDbContext.Count();
            fabricsDbContext = fabricsDbContext.Skip((page - 1) * pageSize).Take(pageSize);
            FabricViewModel fabrics = new FabricViewModel
            {
                fabrics = fabricsDbContext,
                PageViewModel = new PageViewModel(count, page, pageSize),
                Name = fabricView.Name,
                NameofService = fabricView.NameofService,
                TypeofWork = fabricView.TypeofWork,
                CodeTnved = fabricView.CodeTnved,
                CodeOkrb = fabricView.CodeOkrb
            };
            return View(fabrics);
        }

        [HttpPost]
        public IActionResult Index(FabricViewModel fabricView)
        {
            HttpContext.Session.Set("Fabric", fabricView);

            return RedirectToAction("Index");
        }

        // GET: Fabrics/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fabric = await _context.Fabrics
                .Include(f => f.ForWhat)
                .Include(f => f.SetviceName)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fabric == null)
            {
                return NotFound();
            }

            return View(fabric);
        }

        // GET: Fabrics/Create
        public IActionResult Create()
        {
            ViewData["ForWhatId"] = new SelectList(_context.ForWhats, "Id", "TypeofWork");
            ViewData["SetviceNameId"] = new SelectList(_context.ServiceNames, "Id", "NameofService");
            return View();
        }

        // POST: Fabrics/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,SetviceNameId,ForWhatId,CodeTnved,CodeOkrb")] Fabric fabric)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fabric);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ForWhatId"] = new SelectList(_context.ForWhats, "Id", "TypeofWork", fabric.ForWhatId);
            ViewData["SetviceNameId"] = new SelectList(_context.ServiceNames, "Id", "NameofService", fabric.SetviceNameId);
            return View(fabric);
        }

        // GET: Fabrics/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fabric = await _context.Fabrics.FindAsync(id);
            if (fabric == null)
            {
                return NotFound();
            }
            ViewData["ForWhatId"] = new SelectList(_context.ForWhats, "Id", "TypeofWork", fabric.ForWhatId);
            ViewData["SetviceNameId"] = new SelectList(_context.ServiceNames, "Id", "NameofService", fabric.SetviceNameId);
            return View(fabric);
        }

        // POST: Fabrics/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,SetviceNameId,ForWhatId,CodeTnved,CodeOkrb")] Fabric fabric)
        {
            if (id != fabric.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fabric);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FabricExists(fabric.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ForWhatId"] = new SelectList(_context.ForWhats, "Id", "TypeofWork", fabric.ForWhatId);
            ViewData["SetviceNameId"] = new SelectList(_context.ServiceNames, "Id", "NameofService", fabric.SetviceNameId);
            return View(fabric);
        }

        // GET: Fabrics/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fabric = await _context.Fabrics
                .Include(f => f.ForWhat)
                .Include(f => f.SetviceName)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fabric == null)
            {
                return NotFound();
            }

            return View(fabric);
        }

        // POST: Fabrics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fabric = await _context.Fabrics.FindAsync(id);
            if (fabric != null)
            {
                _context.Fabrics.Remove(fabric);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FabricExists(int id)
        {
            return _context.Fabrics.Any(e => e.Id == id);
        }

        private IQueryable<Models.Fabric> Search(IQueryable<Models.Fabric> fabrics, string Name, string NameofService,
           string TypeofWork, string CodeTnved, string CodeOkrb)
        {
            fabrics = fabrics.Where(o => o.Name.Contains(Name ?? "")
           && (o.SetviceName.NameofService.Contains(NameofService ?? ""))
           && (o.ForWhat.TypeofWork.Contains(TypeofWork ?? ""))
           && (o.CodeTnved.Contains(CodeTnved ?? ""))
           && (o.CodeOkrb.Contains(CodeOkrb ?? "")));

            return fabrics;
        }
    }
}

Practic/Controllers/FirmsController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Practic;
using Practic.Models;
using Practic.ViewModels;
using Practic.Infrastructure;

namespace Practic.Controllers
{
    public class FirmsController : Controller
    {
        private readonly PracticdataContext _context;
        private readonly int pageSize = 6;

        public FirmsController(PracticdataContext context)
        {
            _context = context;
        }

        // GET: Firms
        public IActionResult Index(int page = 1)
        {
            var firmView = HttpContext.Session.Get<FirmViewModel>("Firm");
            if (firmView == null)
            {
                firmView = new FirmViewModel();
            }

            IQueryable<Firm> firmsDbContext = _context.Firms;
            firmsDbContext = Search(firmsDbContext, firmView.NameofFirm, firmView.СountryofFirm);
            var count = firmsDbContext.Count();
            firmsDbContext = firmsDbContext.Skip((page - 1) * pageSize).Take(pageSize);
            FirmViewModel firms = new FirmViewModel
            {
                firms = firmsDbContext,
                PageViewModel = new PageViewModel(count, page, pageSize),
                NameofFirm = firmView.NameofFirm,
                СountryofFirm = firmView.СountryofFirm
            };
            return View(firms);
        }

        [HttpPost]
        public IActionResult Index(FirmViewModel firmView)
        {
            HttpContext.Session.Set("Firm", firmView);

            return RedirectToAction("Index");
        }

        // GET: Firms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var firm = await _context.Firms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (firm == null)
            {
                return NotFound();
            }

            return View(firm);
        }

        // GET: Firms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Firms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,СountryofFirm,NameofFirm")] Firm firm)
        {
            if (ModelState.IsValid)
            {
                _context.Add(firm);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(firm);
        }

        // GET: Firms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var firm = await _context.Firms.FindAsync(id);
            if (firm == null)
            {
                return NotFound();
            }
            return View(firm);
        }

        // POST: Firms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,СountryofFirm,NameofFirm")] Firm firm)
        {
            if (id != firm.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(firm);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FirmExists(firm.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(firm);
        }

        // GET: Firms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var firm = await _context.Firms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (firm == null)
            {
                return NotFound();
            }

            return View(firm);
        }

        // POST: Firms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var firm = await _context.Firms.FindAsync(id);
            if (firm != null)
            {
                _context.Firms.Remove(firm);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FirmExists(int id)
        {
            return _context.Firms.Any(e => e.Id == id);
        }

        private IQueryable<Firm> Search(IQueryable<Firm> firms, string NameofFirm, string CountryofFirm)
        {
            firms = firms.Where(o => o.NameofFirm.Contains(NameofFirm ?? "")
           && (o.СountryofFirm.Contains(CountryofFirm ?? "")));

            return firms;
        }
    }
}

Practic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practic</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Practic.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap.css" />
</head>
<body>
    <header>
        <nav nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practic</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Applications" asp-action="Index">Заявка</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Fabrics" asp-action="Index">Материал</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Currencies" asp-action="Index">Валюта</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Firms" asp-action="Index">Фирма</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ForWhats" asp-action="Index">Вид работ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ServiceNames" asp-action="Index">Служба</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  @*  <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Practic - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/css/bootstrap.css"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>